### ISSUE TITLE
Zero-One Knapsack

### ISSUE THREAD

**Issue by Radhika403** [theutpal01/HacktoberFest2022#126]
Hey, I want to contribute my code for the zero-one knapsack problem in Java. Kindly Assign this to me under hacktoberfest 2022 tag.

**Comment by Radhika403** [comment]
PR -> https://github.com/theutpal01/HacktoberFest2022/pull/129

**Comment by Hack7023** [comment]
i want to add the code in python.

**Comment by roopika253** [comment]
I want to add the code in python. Please assign this issue task to me .
