### ISSUE TITLE
calculator using python

### ISSUE THREAD

**Issue by debjitpurohit** [theutpal01/HacktoberFest2022#192]
sir , I am a hacktoberfest 2022 participant . can u please assign me this issue

**Comment by shrutiso05** [comment]
@theutpal01 I want to do this task can you assign me

**Comment by aditya1292** [comment]
Hi! , Please assign me this issue.

**Comment by roopika253** [comment]
Please assign this to me

**Comment by nisthajnn** [comment]
please assign this to me
