### ISSUE TITLE
Quick sort

### ISSUE THREAD

**Issue by Tanmaybhujade** [theutpal01/HacktoberFest2022#233]

**Comment by Tanmaybhujade** [comment]
Quick sort

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by Mohitt0** [comment]
@Tanmaybhujade 
 assign to me

**Comment by yashvardhansingh15** [comment]
@Tanmaybhujade Please assign this issue to me

**Comment by rajsingh16** [comment]
@Tanmaybhujade can you assign this issue to me to start my journey in this open community

**Comment by karna3813** [comment]
@Tanmaybhujade sir please assign this issue to me

**Comment by yashvardhansingh15** [comment]
Can you please assign this issue to me, as recently , as recently I have
practised questions on n sorting

**Comment by RitwikGanguly** [comment]
@Tanmaybhujade can you please assign me in this problem, I can solve this using O(nlogn) time complexity and also I want to contribute  in some basic data science project into your repo.............

**Comment by Pranjal2870** [comment]
@Tanmaybhujade Sir please assign this issue to me

**Comment by ankitk84** [comment]
hey, Tanmaybhujade can you assign it to me. I just started open source. It'll be me my first contribution. thank you

**Comment by manyadua16** [comment]
#455 
I have made a pr for quick sort if you could check it

**Comment by KhushiiAgarwal** [comment]
Please assign me

**Comment by aditi1807** [comment]
please assign me this issue

**Comment by aquasparoo** [comment]
please assign me this issue...i have a very good knowledge in sorting and searching.

**Comment by ghost** [comment]
can you assign me this issue ? would be more than happy to help the Open-source community

**Comment by Tanmaybhujade** [comment]
> @Tanmaybhujade assign to me

yes you do it

**Comment by ghost** [comment]
> 

Assign me

**Comment by Tanmaybhujade** [comment]
DO it

**Comment by ghost** [comment]
Arey chacha assign toh krdo
