### ISSUE TITLE
Wanted to add Python program to check if the given number is a Disarium Number A number is said to be the Disarium number

### ISSUE THREAD

**Issue by piyush-sri** [theutpal01/HacktoberFest2022#93]
I wanted to add a Python program to check if the given number is a Disarium Number
Definition: A number is said to be the Disarium number when the sum of its digit raised to the power of their respective positions becomes equal to the number itself.

For example, 175 is a Disarium number as follows:

Please assign me this issue.

**Comment by Rahul-Roy-21** [comment]
Please assign me to this

**Comment by piyush-sri** [comment]
I opened a pull request by adding the Disarium.java File please have a look.

**Comment by Rahul-Roy-21** [comment]
I just opened the Pull request with no merge conflicts, please have a look and merge
