### ISSUE TITLE
Palindromic partitioning of a string, a Dynamic Programming concept

### ISSUE THREAD

**Issue by Rahul-Roy-21** [theutpal01/HacktoberFest2022#94]
I want to add a CPP and Python solution for Palindromic partitioning question in DP. It finds the fewest number of partitioning in a string so that all the substrings are palindromic

**Comment by Rahul-Roy-21** [comment]
Please assign me to the this issue

**Comment by LordMahir** [comment]
Can you please assign me this issue? I can help .
